# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 188ce4e4853720a6658b4bcb1bce16b9598879aaab017e553f0f8fe1298d241eba2a320032a9ac37d55684a1d4549e3c9b51af4075e63ff9079883e8c8cfa619

test:
  secret_key_base: ed232a594001963e8182ad8ea0c14031581563b2340763bc3ce90dc5aca00f3cf51760165105eef943c6b438d19f7d1a61c96b5b5cb42536ef78de35d5b4fb99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
